{{- if .Values.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "c8-k8s-agent.fullname" . }}
  labels:
    {{- include "c8-k8s-agent.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "c8-k8s-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "c8-k8s-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
