name: Tests
on:
  push:
    branches:
    - main
  pull_request:

env:
  NODE_VERSION: 18

jobs:
  scan:
    name: Trivy scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run Lint
        run: |
          npm run lint